#!/usr/bin/env python3
"""
Create train-only LanceDB retrieval indices from AlfWorld gold trajectories.

This script creates a LanceDB table for AlfWorld trajectories where each entry
represents a step in a trajectory with rich metadata and embedded representations.

IMPORTANT: The last step in each trajectory is IGNORED as it's an erroneous extra step.

Installation:
    # Make sure to install in your conda environment, not user directory
    pip install --upgrade transformers
    pip install lancedb sentence-transformers

    # For Mac with Apple Silicon (M1/M2/M3):
    # pip install torch torchvision torchaudio

    # For CUDA GPU:
    # pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Usage:
    python traj_retrieval/preprocess/alfworld/create_seq_to_seq_indices_train_only.py
"""

import json
import os
import sys
import uuid
import shutil
from typing import Dict, List
from tqdm import tqdm
from pathlib import Path
import glob

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

# Import lancedb
try:
    import lancedb
    import pyarrow as pa
except ImportError:
    print("ERROR: lancedb or pyarrow not found in current environment")
    print("Please install with: pip install lancedb pyarrow")
    sys.exit(1)

# Import sentence transformers
try:
    from sentence_transformers import SentenceTransformer
except ImportError as e:
    print("ERROR: sentence-transformers not found or has dependency issues")
    print(f"Error details: {e}")
    print("\nPlease install/update dependencies with:")
    print("  pip install --upgrade transformers")
    print("  pip install sentence-transformers")
    sys.exit(1)

try:
    from .trajectory_entry import (
        TrajectoryEntry,
        AGENT_TYPE,
        ENVIRONMENT,
        STORAGE_STRATEGY,
        AGENT_FRAMEWORK,
        VERSION,
    )
except ImportError:
    # Support running as a standalone script from repo root.
    from traj_retrieval.preprocess.alfworld.trajectory_entry import (
        TrajectoryEntry,
        AGENT_TYPE,
        ENVIRONMENT,
        STORAGE_STRATEGY,
        AGENT_FRAMEWORK,
        VERSION,
    )

# ============================================================================
# GLOBAL CONFIGURATION - Edit these paths as needed
# ============================================================================

# Path to gold trajectories directory (contains subdirectories with JSON files)
GOLD_TRAJECTORIES_PATH = (
    os.path.join(os.environ.get("MATM_DATA_ROOT", "environments"), "alfworld/traj_logs/run_gold")
)

# Preferred train-only source manifest generated by create_data_splits_train_only.py
TRAIN_INDEX_SOURCE_MANIFEST = (
    "traj_retrieval/preprocess/new_splits/alfworld/train/index_source_train_all.json"
)

# Base output directory for train-only ALFWorld artifacts
TRAIN_ONLY_BASE_DIR = os.path.join(os.environ.get("MATM_DATA_ROOT", "environments"), "train_only_lancedb/alfworld")

# LanceDB configuration
LANCEDB_URI = f"{TRAIN_ONLY_BASE_DIR}/lancedb_indices"
TABLE_NAME = "alfworld"

# Gold repository for storing organized trajectories
GOLD_REPO_PATH = f"{TRAIN_ONLY_BASE_DIR}/intermediate/gold_repo"

# Sentence transformer model to use for embeddings
EMBEDDING_MODEL = "intfloat/e5-base"

# Embedding dimension for the model (intfloat/e5-base produces 768-dimensional embeddings)
EMBEDDING_DIM = 768

# TEST MODE: Set to None for full run, or a number (e.g., 5) to limit total entries for testing
TEST = None  # Set to 5 or 10 for quick testing, None for full run

# BATCH SIZE: Number of entries to accumulate before adding to table
BATCH_SIZE = 500  # Update table every 100 entries

# ============================================================================


def check_environment():
    """Check if the environment is properly set up."""
    print("Checking environment...")

    # Check PyTorch
    try:
        import torch

        print(f"✓ PyTorch version: {torch.__version__}")

        # Check device availability
        if torch.cuda.is_available():
            print(f"✓ CUDA available: {torch.cuda.get_device_name(0)}")
        elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
            print("✓ Apple MPS (Metal) available")
        else:
            print("✓ Running on CPU")
    except ImportError:
        print("⚠ PyTorch not found - will use CPU")

    # Check transformers version
    try:
        import transformers

        print(f"✓ Transformers version: {transformers.__version__}")
    except ImportError:
        print("✗ Transformers not found")
        return False

    print("Environment check complete!\n")
    return True


# ============================================================================


class LanceDBTrajectoryIndexer:
    """Main indexer class for creating LanceDB trajectory database."""

    def __init__(
        self, model_name: str = EMBEDDING_MODEL, gold_repo_path: str = GOLD_REPO_PATH
    ):
        """
        Initialize the indexer with a sentence transformer model.

        Args:
            model_name: Name of the sentence transformer model to use
            gold_repo_path: Path to the gold repository for saving organized trajectories
        """
        print(f"Loading embedding model: {model_name}")
        self.model = SentenceTransformer(model_name)
        self.entry_creator = TrajectoryEntry(self.model, model_name)
        self.db = None
        self.table = None
        self.seen_keys = set()  # For vector DB deduplication
        self.gold_repo_path = Path(gold_repo_path)
        self.gold_repo_path.mkdir(parents=True, exist_ok=True)
        self.gold_repo_duplicates = 0  # Track gold_repo duplicates
        print(f"Gold repository path: {self.gold_repo_path}")

    def connect_db(self, uri: str = LANCEDB_URI):
        """Connect to LanceDB database."""
        os.makedirs(uri, exist_ok=True)
        print(f"Connecting to LanceDB at {uri}...")
        self.db = lancedb.connect(uri)
        print("Connected successfully!")

    def create_indices(self, gold_trajectories_path: str, force: bool = False):
        """
        Create LanceDB table with all trajectory entries.
        Updates table incrementally every BATCH_SIZE entries.

        Args:
            gold_trajectories_path: Path to the directory containing gold trajectory subdirectories
            force: If True, drop the existing table before rebuilding.
        """
        # Connect to database
        self.connect_db()

        # Check if table already exists - if so, exit (or drop, with --force)
        table_names = self.db.table_names()
        if TABLE_NAME in table_names:
            if force:
                print(f"⚠️  Dropping existing table '{TABLE_NAME}' (--force)")
                self.db.drop_table(TABLE_NAME)
            else:
                print(f"\n{'='*70}")
                print(f"ERROR: Table '{TABLE_NAME}' already exists!")
                print(f"Rerun with --force to drop and rebuild, or delete it manually.")
                print(f"{'='*70}\n")
                sys.exit(1)

        # Find all JSON files in subdirectories
        print(f"Scanning for TRAIN trajectory files in {gold_trajectories_path}...")
        json_files = self._find_trajectory_files(gold_trajectories_path)

        print(f"Found {len(json_files)} trajectory files")

        if TEST is not None:
            print(f"\n⚠️  TEST MODE: Creating only {TEST} entries for testing\n")

        # Batch processing
        batch_entries = []
        total_entries_created = 0
        total_duplicates_skipped = 0

        # Process each trajectory file with progress bar
        for json_file in tqdm(json_files, desc="Processing trajectories", unit="file"):
            # Process this trajectory file with deduplication
            entries, duplicates = self._process_trajectory_file(json_file)
            total_duplicates_skipped += duplicates

            if TEST is not None:
                remaining = TEST - total_entries_created - len(batch_entries)
                if remaining <= 0:
                    break
                entries = entries[:remaining]

            batch_entries.extend(entries)

            # Add batch to table if we've accumulated enough entries
            while len(batch_entries) >= BATCH_SIZE:
                batch_to_add = batch_entries[:BATCH_SIZE]
                batch_entries = batch_entries[BATCH_SIZE:]

                self._add_to_table(batch_to_add)
                total_entries_created += len(batch_to_add)

                # Check if we've reached TEST limit
                if TEST is not None and total_entries_created >= TEST:
                    print(f"\n✓ Reached TEST limit of {TEST} entries. Stopping...")
                    break

            # Check if we've reached TEST limit
            if TEST is not None and total_entries_created >= TEST:
                break

        # Add remaining entries
        if batch_entries and (TEST is None or total_entries_created < TEST):
            if TEST is not None:
                batch_entries = batch_entries[: TEST - total_entries_created]
            self._add_to_table(batch_entries)
            total_entries_created += len(batch_entries)

        print(f"\n✓ Total entries added to LanceDB: {total_entries_created:,}")
        print(f"✓ Vector DB duplicate entries skipped: {total_duplicates_skipped:,}")
        print(
            f"✓ Gold repo duplicate trajectories skipped: {self.gold_repo_duplicates:,}"
        )
        print(f"\n✓ All entries saved to LanceDB table '{TABLE_NAME}'")
        print(f"✓ Unique trajectories saved to gold_repo: {GOLD_REPO_PATH}")
        print(
            "\n⚠️  IMPORTANT: Run create_lancedb_index_train_only.py "
            "to create vector index for efficient search!"
        )

    def _find_trajectory_files(self, base_path: str) -> List[str]:
        """
        Find train-only trajectory files.

        Priority:
        1. If TRAIN_INDEX_SOURCE_MANIFEST exists, use trajectory_file entries from it.
        2. Otherwise scan run_* directories and keep files with split=="train".

        Args:
            base_path: Base path to search

        Returns:
            List of JSON file paths
        """
        manifest_path = Path(TRAIN_INDEX_SOURCE_MANIFEST)
        if manifest_path.exists():
            with open(manifest_path, "r") as f:
                manifest_entries = json.load(f)

            manifest_files: List[str] = []
            for item in manifest_entries:
                trajectory_file = item.get("trajectory_file")
                if not trajectory_file:
                    continue
                if os.path.exists(trajectory_file):
                    manifest_files.append(trajectory_file)

            # Deduplicate while preserving deterministic order.
            manifest_files = sorted(set(manifest_files))
            print(
                f"Using train-only manifest: {manifest_path} "
                f"({len(manifest_files)} existing files)"
            )
            return manifest_files

        print(
            f"Train manifest not found at {manifest_path}. "
            "Falling back to scanning run_* files with split=train filter."
        )

        json_files = []

        # Search in all subdirectories
        for subdir in glob.glob(os.path.join(base_path, "run_*")):
            if os.path.isdir(subdir):
                # Find all JSON files in this subdirectory
                files = glob.glob(os.path.join(subdir, "*.json"))
                for file_path in files:
                    try:
                        with open(file_path, "r") as f:
                            data = json.load(f)
                        if data.get("split") == "train":
                            json_files.append(file_path)
                    except Exception:
                        # Skip unreadable files.
                        continue

        return sorted(json_files)

    def _save_trajectory_to_gold_repo(
        self,
        trajectory_data: dict,
        trajectory_id: str,
        task_type: str,
        variation_id: str,
        source_file: str,
    ):
        """
        Save trajectory to gold_repo organized by task_type and variation_id.

        Includes deduplication: If an identical trajectory already exists in the same
        variation_id folder, returns the existing file path instead of creating a duplicate.

        Directory structure: gold_repo/{task_type}/{variation_id}/{trajectory_id}.json

        Each saved trajectory includes:
        - All original trajectory data
        - trajectory_id: UUID for this trajectory
        - source_file: Original file path in run_gold
        - metadata_info: Agent and system configuration (agent_type, environment, etc.)

        Args:
            trajectory_data: Complete trajectory data dictionary
            trajectory_id: Unique trajectory ID
            task_type: Task type (e.g., pick_and_place_simple)
            variation_id: Variation ID (e.g., train-fp228-KeyChain-None-Sofa)
            source_file: Original source file path (for reference)

        Returns:
            Tuple of (output_file_path, is_duplicate)
        """
        # Create directory structure
        task_dir = self.gold_repo_path / task_type
        variation_dir = task_dir / variation_id
        variation_dir.mkdir(parents=True, exist_ok=True)

        # Check for duplicates in this variation_id folder
        # Compare based on core trajectory data (excluding metadata we add)
        core_data_keys = [
            "task_id",
            "task_type",
            "split",
            "floor_plan",
            "goal",
            "trajectory",
            "num_steps",
            "game_file",
        ]

        # Create signature from core data for comparison
        core_data = {
            k: trajectory_data.get(k) for k in core_data_keys if k in trajectory_data
        }
        core_data_str = json.dumps(core_data, sort_keys=True)

        # Check existing files in this variation folder
        for existing_file in variation_dir.glob("*.json"):
            try:
                with open(existing_file, "r") as f:
                    existing_data = json.load(f)

                # Extract core data from existing file
                existing_core = {
                    k: existing_data.get(k)
                    for k in core_data_keys
                    if k in existing_data
                }
                existing_core_str = json.dumps(existing_core, sort_keys=True)

                # If core data matches, it's a duplicate
                if core_data_str == existing_core_str:
                    return (
                        str(existing_file),
                        True,
                    )  # Return existing file, mark as duplicate

            except (json.JSONDecodeError, IOError):
                # Skip corrupted files
                continue

        # No duplicate found, save new trajectory
        # Add metadata info to the data
        trajectory_data_copy = trajectory_data.copy()
        trajectory_data_copy["trajectory_id"] = trajectory_id
        trajectory_data_copy["source_file"] = source_file

        # Add agent and system metadata
        trajectory_data_copy["metadata_info"] = {
            "agent_type": AGENT_TYPE,
            "environment": ENVIRONMENT,
            "storage_strategy": STORAGE_STRATEGY,
            "agent_framework": AGENT_FRAMEWORK,
            "version": VERSION,
        }

        # Save trajectory file
        output_file = variation_dir / f"{trajectory_id}.json"
        with open(output_file, "w") as f:
            json.dump(trajectory_data_copy, f, indent=2)

        return str(output_file), False  # Return new file, not a duplicate

    def _process_trajectory_file(self, json_file: str) -> tuple:
        """
        Process a single trajectory JSON file with deduplication.
        Also saves the trajectory to gold_repo organized by task and variation.

        Args:
            json_file: Path to the JSON file

        Returns:
            Tuple of (entries list, duplicates count)
        """
        # Load the trajectory file
        with open(json_file, "r") as f:
            data = json.load(f)

        # Extract trajectory metadata
        task_id = data["task_id"]
        task_type = data["task_type"]
        split = data["split"]
        floor_plan = data["floor_plan"]
        goal = data["goal"]
        game_file = data.get("game_file", "")
        trajectory = data["trajectory"]

        # Hard guard: this script builds train-only index.
        if split != "train":
            return [], 0

        # CRITICAL: Remove the last step (it's an erroneous extra step)
        if len(trajectory) > 0:
            trajectory = trajectory[:-1]

        if len(trajectory) == 0:
            print(
                f"Warning: Trajectory {task_id} has no steps after removing last step"
            )
            return [], 0

        # Generate a unique trajectory ID
        trajectory_id = str(uuid.uuid4())

        # Create variation_id (using the same method as TrajectoryEntry)
        variation_id = TrajectoryEntry._create_variation_id(game_file, split)

        # Save trajectory to gold_repo (with deduplication)
        # Update the data with the corrected trajectory (last step removed)
        data_to_save = data.copy()
        data_to_save["trajectory"] = trajectory
        saved_file, is_gold_repo_duplicate = self._save_trajectory_to_gold_repo(
            trajectory_data=data_to_save,
            trajectory_id=trajectory_id,
            task_type=task_type,
            variation_id=variation_id,
            source_file=json_file,
        )

        # Track gold_repo duplicates (but still process for vector DB)
        # Vector DB has its own deduplication based on key_signature
        if is_gold_repo_duplicate:
            self.gold_repo_duplicates += 1

        entries = []
        duplicate_count = 0

        # For each step in the trajectory, create an entry
        for i in range(len(trajectory)):
            entry = self.entry_creator.create_entry(
                trajectory_id=trajectory_id,
                task_id=task_id,
                task_type=task_type,
                goal=goal,
                floor_plan=floor_plan,
                game_file=game_file,
                split=split,
                trajectory=trajectory,
                current_step_idx=i,
            )

            # Check for duplicate based on key_raw fields
            key_signature = (
                entry["key_raw_goal"],
                entry["key_raw_state"],
                entry["key_raw_context"],
                entry["key_raw_progress"],
                entry["key_raw_constraints"],
            )

            if key_signature in self.seen_keys:
                duplicate_count += 1
                continue  # Skip duplicate

            # Add to seen keys and entries list
            self.seen_keys.add(key_signature)
            entries.append(entry)

            # Check if we've reached TEST limit
            if TEST is not None and len(entries) >= TEST:
                return entries, duplicate_count

        return entries, duplicate_count

    def _add_to_table(self, entries: List[Dict]):
        """
        Add entries to LanceDB table incrementally with fixed-size vector schema.
        Creates table on first call, appends on subsequent calls.

        Args:
            entries: List of entry dictionaries to add
        """
        if not entries:
            return

        if self.table is None:
            # First batch - create table with explicit schema for fixed-size vectors
            print(
                f"Creating table '{TABLE_NAME}' with first batch of {len(entries)} entries..."
            )
            print("  Using fixed-size vector schema for efficient indexing...")

            # Convert to pandas first to infer most field types
            import pandas as pd

            df = pd.DataFrame(entries)

            # Create PyArrow table with inferred schema
            arrow_table = pa.Table.from_pandas(df)

            # Modify schema to use fixed-size lists for vector columns
            new_fields = []
            vector_columns = ["goal_only", "state_only", "context_only", "key_embed"]

            for field in arrow_table.schema:
                if field.name in vector_columns:
                    # Replace with fixed-size list
                    new_field = pa.field(
                        field.name, pa.list_(pa.float32(), EMBEDDING_DIM)
                    )
                    new_fields.append(new_field)
                else:
                    new_fields.append(field)

            # Create new schema with fixed-size vectors
            fixed_schema = pa.schema(new_fields)

            # Create new arrow table with fixed schema
            arrow_table_fixed = pa.Table.from_pandas(df, schema=fixed_schema)

            # Create LanceDB table
            self.table = self.db.create_table(TABLE_NAME, data=arrow_table_fixed)
            print(f"✓ Table created with {len(entries)} entries and fixed-size vectors")
        else:
            # Subsequent batches - convert to match schema and append
            import pandas as pd

            df = pd.DataFrame(entries)
            arrow_table = pa.Table.from_pandas(df, schema=self.table.schema)
            self.table.add(arrow_table)
            print(f"✓ Added {len(entries)} entries (total: {len(self.table):,})")


def main():
    """Main function to create indices."""
    global TEST

    import argparse

    parser = argparse.ArgumentParser(
        description="Build the ALFWorld train-only LanceDB trajectory index.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Drop the existing LanceDB table before rebuilding (default: refuse and exit).",
    )
    parser.add_argument(
        "--test-entries",
        type=int,
        default=None,
        help="Build only this many LanceDB entries for a fast smoke index.",
    )
    args = parser.parse_args()
    if args.test_entries is not None:
        if args.test_entries <= 0:
            parser.error("--test-entries must be a positive integer")
        TEST = args.test_entries

    print("=" * 70)
    print("AlfWorld Train-Only LanceDB Trajectory Indexer")
    print("=" * 70)
    print(f"Gold trajectories: {GOLD_TRAJECTORIES_PATH}")
    print(f"Train source manifest: {TRAIN_INDEX_SOURCE_MANIFEST}")
    print(f"Gold repository: {GOLD_REPO_PATH}")
    print(f"LanceDB URI: {LANCEDB_URI}")
    print(f"Table name: {TABLE_NAME}")
    print(f"Embedding model: {EMBEDDING_MODEL}")
    print(f"Embedding dimension: {EMBEDDING_DIM} (fixed-size vectors)")
    print(f"Batch size: {BATCH_SIZE} entries")
    if TEST is not None:
        print(f"TEST MODE: Limiting to {TEST} entries")
    print("=" * 70)
    print()

    # Check environment
    if not check_environment():
        print("\nERROR: Environment check failed. Please install missing dependencies.")
        sys.exit(1)

    # Verify input path exists
    if not os.path.exists(GOLD_TRAJECTORIES_PATH):
        print(f"ERROR: Gold trajectories path not found: {GOLD_TRAJECTORIES_PATH}")
        sys.exit(1)

    # Create indexer
    indexer = LanceDBTrajectoryIndexer(model_name=EMBEDDING_MODEL)

    # Create indices
    indexer.create_indices(GOLD_TRAJECTORIES_PATH, force=args.force)

    print("\n" + "=" * 70)
    print("✓ Indexing completed successfully!")
    print("=" * 70)


if __name__ == "__main__":
    main()
