[tox]
minversion = 3.8.0
envlist = flake8

[gh-actions]
python =
    3.10: flake8

[testenv:flake8]
basepython = python3.10
deps = flake8
commands = flake8 --max-line-length 120 ltr traj_retrieval setup_environments.py
