#!/usr/bin/env python3
"""
Create LanceDB indices from staged trajectories.

This generic script:
1. Reads trajectories from gold_repo_stage
2. Checks for duplicates in gold_repo (file-level deduplication)
3. Creates embeddings and LanceDB entries
4. Breaks trajectories into chunks (one entry per step)
5. Moves processed trajectories from gold_repo_stage to gold_repo

Deduplication:
- File-level: Compares entire trajectory content with existing files in gold_repo
  (skips if duplicate found based on model, trajectory, split, task fields)
- Entry-level: Compares key_embed vectors with existing LanceDB entries
  (skips individual entries if duplicate found)

Directory Structure:
- Input: gold_repo_stage/{task_name}/{variation_idx}/{trajectory_id}.json
  Example: gold_repo_stage/intent_template_id_14/task_id_42/abc123.json
- Output: gold_repo/{task_name}/{variation_idx}/{trajectory_id}.json

Task Naming Convention:
- task_name: intent_template_id_{id} (e.g., "intent_template_id_14")
- variation_idx: task_id_{task_id} (e.g., "task_id_42")

Usage:
    python traj_retrieval/preprocess/webarena/create_lancedb_indices_train_only.py
"""
import json
import os
import sys
import shutil
from typing import Dict, List, Optional, Set, Tuple
from tqdm import tqdm
from pathlib import Path

try:
    import lancedb
    import pyarrow as pa
    import numpy as np
except ImportError:
    print("ERROR: lancedb, pyarrow, or numpy not found")
    print("Install with: pip install lancedb pyarrow numpy")
    sys.exit(1)

try:
    from sentence_transformers import SentenceTransformer
except ImportError as e:
    print("ERROR: sentence-transformers not found")
    print(f"Error: {e}")
    print("Install with: pip install --upgrade transformers sentence-transformers")
    sys.exit(1)

# Allow running this script from any cwd: prepend its own directory so the
# sibling `trajectory_entry` module resolves regardless of where the user
# invokes `python …/create_lancedb_indices_train_only.py` from.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from trajectory_entry import TrajectoryEntry  # noqa: E402

# ============================================================================
# CONFIGURATION
# ============================================================================

# Train-only intermediate root
INTERMEDIATE_DIR = (
    os.path.join(os.environ.get("MATM_DATA_ROOT", "environments"), "train_only_lancedb/intermediate/webarena")
)

# Staging directory (input)
GOLD_REPO_STAGE_PATH = f"{INTERMEDIATE_DIR}/gold_repo_stage"

# Final gold repository (output)
GOLD_REPO_PATH = f"{INTERMEDIATE_DIR}/gold_repo"

# LanceDB configuration
LANCEDB_URI = (
    os.path.join(os.environ.get("MATM_DATA_ROOT", "environments"), "train_only_lancedb/webarena/lancedb_indices")
)
TABLE_NAME = "webarena"

# Train-only index source manifest (generated by create_data_splits_train_only.py)
TRAIN_INDEX_SOURCE_MANIFEST = (
    "traj_retrieval/preprocess/new_splits/webarena/train/index_source_train_augmented.json"
)

# Embedding model
EMBEDDING_MODEL = "intfloat/e5-base"
EMBEDDING_DIM = 768

# Batch size for LanceDB updates
BATCH_SIZE = 100

# TEST MODE: Limit entries for testing
TEST = None

# ============================================================================


class LanceDBIndexer:
    """Creates LanceDB indices from staged trajectories."""

    def __init__(self, model_name: str = EMBEDDING_MODEL):
        print(f"Loading embedding model: {model_name}")
        self.model = SentenceTransformer(model_name)
        self.entry_creator = TrajectoryEntry(self.model, model_name)
        self.db = None
        self.table = None
        self.seen_keys = set()
        self.gold_repo_path = Path(GOLD_REPO_PATH)
        self.gold_repo_path.mkdir(parents=True, exist_ok=True)
        self.intermediate_dir = Path(INTERMEDIATE_DIR)
        self.intermediate_dir.mkdir(parents=True, exist_ok=True)

    def connect_db(self, uri: str = LANCEDB_URI):
        """Connect to LanceDB database."""
        os.makedirs(uri, exist_ok=True)
        print(f"Connecting to LanceDB at {uri}...")
        self.db = lancedb.connect(uri)
        print("Connected successfully!")

    def _load_train_manifest(
        self, manifest_path: str
    ) -> Tuple[Optional[Set[Tuple[str, str]]], int]:
        """
        Load train-only manifest as a set of (task_name, variation_id) pairs.
        Returns (None, 0) if manifest doesn't exist.
        """
        manifest_file = Path(manifest_path)
        if not manifest_file.exists():
            print(f"Train manifest not found: {manifest_file}")
            return None, 0

        with manifest_file.open("r", encoding="utf-8") as f:
            manifest_data = json.load(f)

        if not isinstance(manifest_data, list):
            raise ValueError(f"Manifest is not a JSON list: {manifest_file}")

        pair_set: Set[Tuple[str, str]] = set()
        for item in manifest_data:
            task_name = item.get("task_name")
            variation_id = item.get("variation_id")
            if task_name is None or variation_id is None:
                continue
            pair_set.add((str(task_name), str(variation_id)))

        manifest_snapshot = self.intermediate_dir / "manifest_used.json"
        with manifest_snapshot.open("w", encoding="utf-8") as f:
            json.dump(
                {
                    "source_manifest": str(manifest_file),
                    "pairs_count": len(pair_set),
                    "pairs": sorted(list(pair_set)),
                },
                f,
                indent=2,
                ensure_ascii=False,
            )
        print(f"Loaded train manifest: {manifest_file} ({len(pair_set)} pairs)")
        print(f"Manifest snapshot: {manifest_snapshot}")
        return pair_set, len(pair_set)

    def _find_staged_trajectories(self, stage_path: str) -> List[str]:
        """
        Find all staged trajectory files.

        Returns:
            List of paths to staged trajectory JSON files
        """
        stage_path = Path(stage_path)

        if not stage_path.exists():
            return []

        json_files = []
        for task_dir in stage_path.iterdir():
            if not task_dir.is_dir():
                continue

            for variation_dir in task_dir.iterdir():
                if not variation_dir.is_dir():
                    continue

                for json_file in variation_dir.glob("*.json"):
                    json_files.append(str(json_file))

        json_files.sort()
        return json_files

    def _process_staged_trajectory(
        self,
        json_file: str,
        train_pair_set: Optional[Set[Tuple[str, str]]] = None,
    ) -> tuple:
        """
        Process a staged trajectory file and create LanceDB entries.

        Breaks the trajectory into chunks (one entry per step) with embeddings.
        Extracts task_name and variation_idx from the file path structure.

        Args:
            json_file: Path to staged trajectory JSON file

        Returns:
            Tuple of (entries, trajectory_data, duplicates, manifest_filtered)
            - entries: List of LanceDB entry dictionaries (one per step)
            - trajectory_data: Original trajectory data
            - duplicates: Count of duplicate entries skipped
            - manifest_filtered: whether trajectory was filtered out by train manifest
        """
        try:
            with open(json_file, "r") as f:
                data = json.load(f)
        except Exception as e:
            print(f"  ❌ Error loading {json_file}: {e}")
            return [], None, 0, False

        # Extract required fields
        trajectory_id = data.get("trajectory_id")
        if not trajectory_id:
            print(f"  ⚠️ Warning: No trajectory_id in {json_file}, skipping")
            return [], None, 0, False

        trajectory = data.get("trajectory", [])
        if not trajectory:
            return [], None, 0, False

        # Extract metadata from staged file
        metadata_info = data.get("metadata_info", {})
        agent_type = metadata_info.get("agent_type", data.get("model", "unknown"))

        # Get task info from file path: stage_path/task_name/variation_idx/file.json
        # task_name format: intent_template_id_{id}
        # variation_idx format: task_id_{task_id}
        file_path = Path(json_file)
        variation_idx = file_path.parent.name
        task_name = file_path.parent.parent.name

        # Strict train-only filter via manifest pairs.
        if (
            train_pair_set is not None
            and (task_name, variation_idx) not in train_pair_set
        ):
            return [], data, 0, True

        # Get objective from first trajectory step
        objective = trajectory[0].get("objective", "") if trajectory else ""

        # Get optional fields
        split = data.get("split", "test")

        # Extract config metadata (stored during staging)
        # These may or may not exist depending on the trajectory source
        config_task_id = variation_idx  # Use variation_idx from folder structure
        sites = []  # Not critical for indexing
        intent_template = ""  # Not critical for indexing
        intent_template_id = task_name  # Use task_name from folder structure

        entries = []
        duplicate_count = 0

        # Create entries for each step
        for i in range(len(trajectory)):
            entry = self.entry_creator.create_entry(
                trajectory_id=trajectory_id,
                objective=objective,
                trajectory=trajectory,
                current_step_idx=i,
                agent_type=agent_type,
                task_name=task_name,
                variation_idx=variation_idx,
                split=split,
                config_task_id=config_task_id,
                sites=sites,
                intent_template=intent_template,
                intent_template_id=intent_template_id,
            )

            # Check for duplicates based on key_embed
            key_embed_tuple = tuple(entry["key_embed"])

            if key_embed_tuple in self.seen_keys:
                duplicate_count += 1
                continue

            self.seen_keys.add(key_embed_tuple)
            entries.append(entry)

            if TEST is not None and len(entries) >= TEST:
                break

        return entries, data, duplicate_count, False

    def _check_duplicate_in_gold_repo(
        self, trajectory_data: dict, task_name: str, variation_idx: str
    ) -> bool:
        """
        Check if trajectory with identical content already exists in gold_repo.

        Args:
            trajectory_data: Trajectory data to check
            task_name: Task name (intent_template_id_{id})
            variation_idx: Variation ID (task_id_{task_id})

        Returns:
            True if duplicate found, False otherwise
        """
        gold_variation_dir = self.gold_repo_path / task_name / variation_idx

        if not gold_variation_dir.exists():
            return False

        # Compare core data (excluding metadata we add like trajectory_id, source_file)
        core_data_keys = ["model", "trajectory", "split", "task"]
        core_data = {
            k: trajectory_data.get(k) for k in core_data_keys if k in trajectory_data
        }
        core_data_str = json.dumps(core_data, sort_keys=True)

        # Check all existing files in gold_repo for this task_name/variation_idx
        for existing_file in gold_variation_dir.glob("*.json"):
            try:
                with open(existing_file, "r") as f:
                    existing_data = json.load(f)

                existing_core = {
                    k: existing_data.get(k)
                    for k in core_data_keys
                    if k in existing_data
                }
                existing_core_str = json.dumps(existing_core, sort_keys=True)

                if core_data_str == existing_core_str:
                    return True  # Duplicate found

            except (json.JSONDecodeError, IOError):
                continue

        return False  # No duplicate found

    def _move_to_gold_repo(self, staged_file: str, trajectory_data: dict):
        """
        Move trajectory from stage to final gold_repo.

        Preserves the directory structure from staging:
        - stage/{task_name}/{variation_idx}/{trajectory_id}.json
        - gold_repo/{task_name}/{variation_idx}/{trajectory_id}.json

        Where task_name = intent_template_id_{id} and variation_idx = task_id_{task_id}

        Args:
            staged_file: Path to staged file
            trajectory_data: Trajectory data dictionary
        """
        staged_path = Path(staged_file)

        # Extract task_name and variation_idx from staged path
        # stage/{task_name}/{variation_idx}/{trajectory_id}.json
        variation_idx = staged_path.parent.name
        task_name = staged_path.parent.parent.name
        trajectory_id = staged_path.stem

        # Create destination path
        dest_dir = self.gold_repo_path / task_name / variation_idx
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest_file = dest_dir / f"{trajectory_id}.json"

        # Move file
        shutil.move(str(staged_path), str(dest_file))

        # Clean up empty directories in stage
        try:
            staged_path.parent.rmdir()  # Remove variation_idx dir if empty
            staged_path.parent.parent.rmdir()  # Remove task_name dir if empty
        except OSError:
            pass  # Directory not empty, that's okay

    def _add_to_table(self, entries: List[Dict]):
        """Add entries to LanceDB table with fixed-size vector schema."""
        if not entries:
            return

        import pandas as pd

        df = pd.DataFrame(entries)

        # Convert vector columns to numpy arrays
        vector_columns = ["goal_only", "state_only", "context_only", "key_embed"]
        for col in vector_columns:
            df[col] = df[col].apply(lambda x: np.array(x, dtype=np.float32).tolist())

        if self.table is None:
            # Create table with fixed-size vector schema
            print(
                f"Creating table '{TABLE_NAME}' with first batch of {len(entries)} entries..."
            )
            print("  Using fixed-size vector schema...")

            arrow_table = pa.Table.from_pandas(df)

            new_fields = []
            for field in arrow_table.schema:
                if field.name in vector_columns:
                    new_field = pa.field(
                        field.name, pa.list_(pa.float32(), EMBEDDING_DIM)
                    )
                    new_fields.append(new_field)
                else:
                    new_fields.append(field)

            fixed_schema = pa.schema(new_fields)
            arrow_table_fixed = pa.Table.from_pandas(df, schema=fixed_schema)

            self.table = self.db.create_table(TABLE_NAME, data=arrow_table_fixed)
            print(f"✓ Table created with {len(entries)} entries")
        else:
            table_schema = self.table.schema
            if hasattr(table_schema, "to_arrow"):
                table_schema = table_schema.to_arrow()
            arrow_table = pa.Table.from_pandas(df, schema=table_schema)
            self.table.add(arrow_table)
            print(f"✓ Added {len(entries)} entries (total: {len(self.table):,})")

    def create_indices(self, stage_path: str):
        """
        Create LanceDB indices from staged trajectories.

        Deduplication Strategy:
        1. File-level: Checks if trajectory content already exists in gold_repo
           - Compares core data (model, trajectory, split, task)
           - Skips entire file if duplicate found
        2. Entry-level: Checks if LanceDB entries already exist
           - Compares key_embed vectors
           - Skips individual entries if duplicate found

        Args:
            stage_path: Path to gold_repo_stage directory
        """
        self.connect_db()

        # Load strict train-only manifest.
        train_pair_set, train_pair_count = self._load_train_manifest(
            TRAIN_INDEX_SOURCE_MANIFEST
        )
        if not train_pair_set:
            raise RuntimeError(
                f"Train manifest is required for train-only indexing: {TRAIN_INDEX_SOURCE_MANIFEST}"
            )

        # Require clean table for train-only reproducibility.
        table_names = self.db.table_names()
        if TABLE_NAME in table_names:
            print(f"\n{'='*70}")
            print(f"ERROR: Table '{TABLE_NAME}' already exists!")
            print("Please delete the existing table before running this script.")
            print(f"{'='*70}\n")
            sys.exit(1)
        print(f"Creating new table '{TABLE_NAME}'...")

        if TEST is not None:
            print(f"\n⚠️  TEST MODE: Creating only {TEST} entries\n")

        # Find all staged trajectories
        print(f"Scanning for staged trajectories in {stage_path}...")
        staged_files = self._find_staged_trajectories(stage_path)
        print(f"Found {len(staged_files)} staged trajectory files\n")

        if not staged_files:
            print(
                "⚠️  No staged trajectories found. Run stage_gold_trajectories_train_only.py first."
            )
            return

        batch_entries = []
        total_entries_created = 0
        total_duplicates = 0
        total_moved = 0
        total_skipped_gold_repo_duplicates = 0
        total_manifest_filtered = 0

        for staged_file in tqdm(
            staged_files, desc="Processing staged trajectories", unit="file"
        ):
            (
                entries,
                trajectory_data,
                duplicates,
                manifest_filtered,
            ) = self._process_staged_trajectory(
                staged_file,
                train_pair_set=train_pair_set,
            )

            if manifest_filtered:
                total_manifest_filtered += 1
                continue

            if not trajectory_data:
                continue

            # Check if this trajectory already exists in gold_repo (file content deduplication)
            file_path = Path(staged_file)
            variation_idx = file_path.parent.name
            task_name = file_path.parent.parent.name

            if self._check_duplicate_in_gold_repo(
                trajectory_data, task_name, variation_idx
            ):
                total_skipped_gold_repo_duplicates += 1
                # Remove staged file since it's a duplicate
                Path(staged_file).unlink()
                # Clean up empty directories
                try:
                    file_path.parent.rmdir()
                    file_path.parent.parent.rmdir()
                except OSError:
                    pass
                continue  # Skip processing this trajectory

            # Track LanceDB entry-level duplicates (based on key_embed)
            total_duplicates += duplicates

            if entries:
                batch_entries.extend(entries)

                # Add batch to table
                while len(batch_entries) >= BATCH_SIZE:
                    batch_to_add = batch_entries[:BATCH_SIZE]
                    batch_entries = batch_entries[BATCH_SIZE:]

                    self._add_to_table(batch_to_add)
                    total_entries_created += len(batch_to_add)

                    if TEST is not None and total_entries_created >= TEST:
                        break

            # Move to gold_repo after successful processing (only if not duplicate)
            self._move_to_gold_repo(staged_file, trajectory_data)
            total_moved += 1

            if TEST is not None and total_entries_created >= TEST:
                break

        # Add remaining entries
        if batch_entries and (TEST is None or total_entries_created < TEST):
            if TEST is not None:
                batch_entries = batch_entries[: TEST - total_entries_created]
            self._add_to_table(batch_entries)
            total_entries_created += len(batch_entries)

        print(f"\n{'='*70}")
        print(f"Indexing Summary")
        print(f"{'='*70}")
        print(f"✓ Entries added to LanceDB: {total_entries_created:,}")
        print(f"✓ Duplicate LanceDB entries skipped (key_embed): {total_duplicates:,}")
        print(
            f"✓ Duplicate trajectories skipped (gold_repo content): {total_skipped_gold_repo_duplicates:,}"
        )
        print(f"✓ Manifest-filtered trajectories skipped: {total_manifest_filtered:,}")
        print(f"✓ Trajectories moved to gold_repo: {total_moved:,}")
        print(f"\n✓ LanceDB table: {TABLE_NAME}")
        print(f"✓ Gold repository: {GOLD_REPO_PATH}")
        print(f"\n⚠️  IMPORTANT: Create vector index for efficient search:")
        print(
            f"   indexer.table.create_index(metric='L2', vector_column_name='key_embed')"
        )
        print(f"{'='*70}\n")

        summary_path = self.intermediate_dir / "index_build_summary.json"
        with summary_path.open("w", encoding="utf-8") as f:
            json.dump(
                {
                    "train_manifest": TRAIN_INDEX_SOURCE_MANIFEST,
                    "train_manifest_pairs": train_pair_count,
                    "stage_path": stage_path,
                    "gold_repo_path": GOLD_REPO_PATH,
                    "lancedb_uri": LANCEDB_URI,
                    "table_name": TABLE_NAME,
                    "entries_added": total_entries_created,
                    "duplicate_entries_skipped": total_duplicates,
                    "duplicate_trajectories_skipped": total_skipped_gold_repo_duplicates,
                    "manifest_filtered_trajectories": total_manifest_filtered,
                    "trajectories_moved": total_moved,
                },
                f,
                indent=2,
                ensure_ascii=False,
            )
        print(f"✓ Build summary: {summary_path}")


def main():
    """Main function."""
    print("=" * 70)
    print("WebArena Train-Only LanceDB Indexer")
    print("=" * 70)
    print(f"Stage path: {GOLD_REPO_STAGE_PATH}")
    print(f"Gold repository: {GOLD_REPO_PATH}")
    print(f"LanceDB URI: {LANCEDB_URI}")
    print(f"Intermediate dir: {INTERMEDIATE_DIR}")
    print(f"Train manifest: {TRAIN_INDEX_SOURCE_MANIFEST}")
    print(f"Table name: {TABLE_NAME}")
    print(f"Embedding model: {EMBEDDING_MODEL}")
    print(f"Embedding dimension: {EMBEDDING_DIM}")
    print(f"Batch size: {BATCH_SIZE}")
    if TEST is not None:
        print(f"TEST MODE: Limiting to {TEST} entries")
    print("=" * 70)
    print()

    if not os.path.exists(GOLD_REPO_STAGE_PATH):
        print(f"ERROR: Stage path not found: {GOLD_REPO_STAGE_PATH}")
        print("Run stage_gold_trajectories_train_only.py first to stage trajectories.")
        sys.exit(1)

    indexer = LanceDBIndexer(model_name=EMBEDDING_MODEL)
    indexer.create_indices(GOLD_REPO_STAGE_PATH)

    print("\n" + "=" * 70)
    print("✓ Indexing completed successfully!")
    print("=" * 70)


if __name__ == "__main__":
    main()
